
---
- name: VMWare_VM-IDs&pathsInventory_playbook
  hosts: all
  tasks:
  - name: VM-IDs&pathsInventory
    uri:
      url: https://192.168.1.75:8697/api/vms
      validate_certs: no
      user: apereira
      password: 123456!aA
      method: GET
      force_basic_auth: yes
      #status_code: 201
      body_format: json
