---
- name: VMWareRestAPI playbook
  hosts: all
  tasks:
  - name: VMWareRestAPI playbook
    uri:
      validate_cert:no
      url: https://192.168.1.75:8697/api/vmnet
      #user: apereira
      #password: 123456!aA
      method: POST
      force_basic_auth: yes
      status_code: 201
      body_format: json
